name: Deploy to DigitalOcean Production Droplet

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Master Droplet
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout@v3 For Code Checkout
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MIRZA_TEO_THINKPAD_SSH_KEY_FOR_DIGITALOCEAN }}

      - name: Use Git Secrets | Move To The App Root Directory | Git Pull | Composer Install | Artisan Commands
        run: | 
            ssh -p 65000 -o StrictHostKeyChecking=no ${{ secrets.DIGITALOCEAN_PRODUCTION_DROPLET_USER }}@${{ secrets.DIGITALOCEAN_PRODUCTION_DROPLET_IP }} << 'EOF'
            cd /var/www/teekit-by-mirza/ 
            git pull https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/mirza-organization/teekit-by-mirza master
            composer install --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            EOF
          
